name = "nTomo"
uuid = "69649c1d-aa60-4d7f-ab4b-d49044b65f81"
authors = ["Julia-KAERI <julia.kaeri@gmail.com"]
version = "0.3.2"

[deps]
CFITSIO = "3b1b4be9-1499-4b22-8d78-7db3344d1961"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NRRD = "9bb6cfbd-7763-5393-b1b5-1c8e09872146"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
TiffImages = "731e570b-9d59-4bfa-96dc-6df516fadf69"
